# Generated by Django 4.2.9 on 2024-02-09 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_author_pseudonym"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                related_name="books_authors", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
