# Generated by Django 4.2.9 on 2024-02-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_book_authors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ("id",)},
        ),
    ]
